/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables.records;


import codegen.jooq.tables.Applicant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicantRecord extends UpdatableRecordImpl<ApplicantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.APPLICANT.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.APPLICANT.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.APPLICANT.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicantRecord
     */
    public ApplicantRecord() {
        super(Applicant.APPLICANT);
    }

    /**
     * Create a detached, initialised ApplicantRecord
     */
    public ApplicantRecord(String email, String name, String password) {
        super(Applicant.APPLICANT);

        setEmail(email);
        setName(name);
        setPassword(password);
        resetChangedOnNotNull();
    }
}
