/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables.records;


import codegen.jooq.tables.ApplicantCompetence;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicantCompetenceRecord extends UpdatableRecordImpl<ApplicantCompetenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.APPLICANT_COMPETENCE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT_COMPETENCE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.APPLICANT_COMPETENCE.COMPETENCE_ID</code>.
     */
    public void setCompetenceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT_COMPETENCE.COMPETENCE_ID</code>.
     */
    public String getCompetenceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.APPLICANT_COMPETENCE.APPLICANT_EMAIL</code>.
     */
    public void setApplicantEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT_COMPETENCE.APPLICANT_EMAIL</code>.
     */
    public String getApplicantEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.APPLICANT_COMPETENCE.EXPERIENCE</code>.
     */
    public void setExperience(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.APPLICANT_COMPETENCE.EXPERIENCE</code>.
     */
    public Integer getExperience() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicantCompetenceRecord
     */
    public ApplicantCompetenceRecord() {
        super(ApplicantCompetence.APPLICANT_COMPETENCE);
    }

    /**
     * Create a detached, initialised ApplicantCompetenceRecord
     */
    public ApplicantCompetenceRecord(Integer id, String competenceId, String applicantEmail, Integer experience) {
        super(ApplicantCompetence.APPLICANT_COMPETENCE);

        setId(id);
        setCompetenceId(competenceId);
        setApplicantEmail(applicantEmail);
        setExperience(experience);
        resetChangedOnNotNull();
    }
}
