/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables.records;


import codegen.jooq.tables.Company;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.COMPANY.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.BUSINESS_NAME</code>.
     */
    public void setBusinessName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.BUSINESS_NAME</code>.
     */
    public String getBusinessName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.SECTOR</code>.
     */
    public void setSector(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.SECTOR</code>.
     */
    public String getSector() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.COMPANY.CNPJ</code>.
     */
    public void setCnpj(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.COMPANY.CNPJ</code>.
     */
    public String getCnpj() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(Integer id, String businessName, String sector, String description, String email, String password, String cnpj) {
        super(Company.COMPANY);

        setId(id);
        setBusinessName(businessName);
        setSector(sector);
        setDescription(description);
        setEmail(email);
        setPassword(password);
        setCnpj(cnpj);
        resetChangedOnNotNull();
    }
}
