/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables.records;


import codegen.jooq.tables.JobCompetence;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobCompetenceRecord extends UpdatableRecordImpl<JobCompetenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.JOB_COMPETENCE.JOB_ID</code>.
     */
    public void setJobId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB_COMPETENCE.JOB_ID</code>.
     */
    public Integer getJobId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.JOB_COMPETENCE.COMPETENCE_ID</code>.
     */
    public void setCompetenceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB_COMPETENCE.COMPETENCE_ID</code>.
     */
    public String getCompetenceId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobCompetenceRecord
     */
    public JobCompetenceRecord() {
        super(JobCompetence.JOB_COMPETENCE);
    }

    /**
     * Create a detached, initialised JobCompetenceRecord
     */
    public JobCompetenceRecord(Integer jobId, String competenceId) {
        super(JobCompetence.JOB_COMPETENCE);

        setJobId(jobId);
        setCompetenceId(competenceId);
        resetChangedOnNotNull();
    }
}
