/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables.records;


import codegen.jooq.tables.Job;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobRecord extends UpdatableRecordImpl<JobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.JOB.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.JOB.COMPANY_EMAIL</code>.
     */
    public void setCompanyEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.COMPANY_EMAIL</code>.
     */
    public String getCompanyEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.JOB.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.JOB.FIELD</code>.
     */
    public void setField(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.FIELD</code>.
     */
    public String getField() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.JOB.SALARY_RANGE</code>.
     */
    public void setSalaryRange(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.SALARY_RANGE</code>.
     */
    public String getSalaryRange() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.JOB.SKILL</code>.
     */
    public void setSkill(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.SKILL</code>.
     */
    public String getSkill() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.JOB.EXPERIENCE</code>.
     */
    public void setExperience(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.EXPERIENCE</code>.
     */
    public String getExperience() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.JOB.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.JOB.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobRecord
     */
    public JobRecord() {
        super(Job.JOB);
    }

    /**
     * Create a detached, initialised JobRecord
     */
    public JobRecord(Integer id, String companyEmail, String name, String field, String salaryRange, String skill, String experience, String description) {
        super(Job.JOB);

        setId(id);
        setCompanyEmail(companyEmail);
        setName(name);
        setField(field);
        setSalaryRange(salaryRange);
        setSkill(skill);
        setExperience(experience);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
