CREATE TABLE IF NOT EXISTS applicant (
  email VARCHAR(255) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS token (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS company (
  code INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  business_name VARCHAR(255) NOT NULL,
  sector VARCHAR(255) NOT NULL,
  description TEXT,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  cnpj VARCHAR(18) NOT NULL UNIQUE
);

