CREATE TABLE IF NOT EXISTS applicant (
  email VARCHAR(255) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS token (
  id VARCHAR(255) NOT NULL PRIMARY KEY,
  applicant_email VARCHAR(255) NOT NULL,
  FOREIGN KEY (applicant_email) REFERENCES applicant(email)
);

