/*
 * This file is generated by jOOQ.
 */
package codegen.jooq;


import codegen.jooq.tables.Applicant;
import codegen.jooq.tables.Token;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.APPLICANT</code>.
     */
    public static final Applicant APPLICANT = Applicant.APPLICANT;

    /**
     * The table <code>PUBLIC.TOKEN</code>.
     */
    public static final Token TOKEN = Token.TOKEN;
}
