/*
 * This file is generated by jOOQ.
 */
package codegen.jooq;


import codegen.jooq.tables.Applicant;
import codegen.jooq.tables.ApplicantCompetence;
import codegen.jooq.tables.Company;
import codegen.jooq.tables.Competence;
import codegen.jooq.tables.Job;
import codegen.jooq.tables.JobCompetence;
import codegen.jooq.tables.Token;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.APPLICANT</code>.
     */
    public static final Applicant APPLICANT = Applicant.APPLICANT;

    /**
     * The table <code>PUBLIC.APPLICANT_COMPETENCE</code>.
     */
    public static final ApplicantCompetence APPLICANT_COMPETENCE = ApplicantCompetence.APPLICANT_COMPETENCE;

    /**
     * The table <code>PUBLIC.COMPANY</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>PUBLIC.COMPETENCE</code>.
     */
    public static final Competence COMPETENCE = Competence.COMPETENCE;

    /**
     * The table <code>PUBLIC.JOB</code>.
     */
    public static final Job JOB = Job.JOB;

    /**
     * The table <code>PUBLIC.JOB_COMPETENCE</code>.
     */
    public static final JobCompetence JOB_COMPETENCE = JobCompetence.JOB_COMPETENCE;

    /**
     * The table <code>PUBLIC.TOKEN</code>.
     */
    public static final Token TOKEN = Token.TOKEN;
}
