/*
 * This file is generated by jOOQ.
 */
package codegen.jooq.tables;


import codegen.jooq.Keys;
import codegen.jooq.Public;
import codegen.jooq.tables.Competence.CompetencePath;
import codegen.jooq.tables.Job.JobPath;
import codegen.jooq.tables.records.JobCompetenceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobCompetence extends TableImpl<JobCompetenceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.JOB_COMPETENCE</code>
     */
    public static final JobCompetence JOB_COMPETENCE = new JobCompetence();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobCompetenceRecord> getRecordType() {
        return JobCompetenceRecord.class;
    }

    /**
     * The column <code>PUBLIC.JOB_COMPETENCE.JOB_ID</code>.
     */
    public final TableField<JobCompetenceRecord, Integer> JOB_ID = createField(DSL.name("JOB_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.JOB_COMPETENCE.COMPETENCE_ID</code>.
     */
    public final TableField<JobCompetenceRecord, String> COMPETENCE_ID = createField(DSL.name("COMPETENCE_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private JobCompetence(Name alias, Table<JobCompetenceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JobCompetence(Name alias, Table<JobCompetenceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.JOB_COMPETENCE</code> table reference
     */
    public JobCompetence(String alias) {
        this(DSL.name(alias), JOB_COMPETENCE);
    }

    /**
     * Create an aliased <code>PUBLIC.JOB_COMPETENCE</code> table reference
     */
    public JobCompetence(Name alias) {
        this(alias, JOB_COMPETENCE);
    }

    /**
     * Create a <code>PUBLIC.JOB_COMPETENCE</code> table reference
     */
    public JobCompetence() {
        this(DSL.name("JOB_COMPETENCE"), null);
    }

    public <O extends Record> JobCompetence(Table<O> path, ForeignKey<O, JobCompetenceRecord> childPath, InverseForeignKey<O, JobCompetenceRecord> parentPath) {
        super(path, childPath, parentPath, JOB_COMPETENCE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JobCompetencePath extends JobCompetence implements Path<JobCompetenceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JobCompetencePath(Table<O> path, ForeignKey<O, JobCompetenceRecord> childPath, InverseForeignKey<O, JobCompetenceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JobCompetencePath(Name alias, Table<JobCompetenceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JobCompetencePath as(String alias) {
            return new JobCompetencePath(DSL.name(alias), this);
        }

        @Override
        public JobCompetencePath as(Name alias) {
            return new JobCompetencePath(alias, this);
        }

        @Override
        public JobCompetencePath as(Table<?> alias) {
            return new JobCompetencePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<JobCompetenceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_12B8;
    }

    @Override
    public List<ForeignKey<JobCompetenceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_12, Keys.CONSTRAINT_12B);
    }

    private transient JobPath _job;

    /**
     * Get the implicit join path to the <code>PUBLIC.JOB</code> table.
     */
    public JobPath job() {
        if (_job == null)
            _job = new JobPath(this, Keys.CONSTRAINT_12, null);

        return _job;
    }

    private transient CompetencePath _competence;

    /**
     * Get the implicit join path to the <code>PUBLIC.COMPETENCE</code> table.
     */
    public CompetencePath competence() {
        if (_competence == null)
            _competence = new CompetencePath(this, Keys.CONSTRAINT_12B, null);

        return _competence;
    }

    @Override
    public JobCompetence as(String alias) {
        return new JobCompetence(DSL.name(alias), this);
    }

    @Override
    public JobCompetence as(Name alias) {
        return new JobCompetence(alias, this);
    }

    @Override
    public JobCompetence as(Table<?> alias) {
        return new JobCompetence(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobCompetence rename(String name) {
        return new JobCompetence(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobCompetence rename(Name name) {
        return new JobCompetence(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public JobCompetence rename(Table<?> name) {
        return new JobCompetence(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence where(Condition condition) {
        return new JobCompetence(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobCompetence where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobCompetence where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobCompetence where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public JobCompetence where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public JobCompetence whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
